/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#282a2f", 
        "inverse-primary": "#006e15", 
        "surface-dim": "#111318", 
        "on-error-container": "#ffdad6", 
        "surface-tint": "#4de252", 
        "on-secondary-fixed": "#3e0500", 
        "primary-fixed-dim": "#4de252", 
        "on-tertiary-container": "#3f4f5f", 
        "primary-fixed": "#73ff70", 
        "error-container": "#93000a", 
        "on-secondary-container": "#ffe7e2", 
        "surface": "#111318", 
        "tertiary-container": "#afc1d4", 
        "tertiary-fixed-dim": "#b7c8dc", 
        "on-tertiary": "#213241", 
        "primary": "#64f764", 
        "on-surface": "#e2e2e9", 
        "error": "#ffb4ab", 
        "on-secondary": "#640e00", 
        "secondary-container": "#ce2701", 
        "on-primary-fixed-variant": "#00530d", 
        "on-error": "#690005", 
        "on-primary": "#003906", 
        "on-surface-variant": "#bccbb5", 
        "outline": "#869581", 
        "on-primary-container": "#005b0f", 
        "inverse-surface": "#e2e2e9", 
        "on-tertiary-fixed-variant": "#384858", 
        "tertiary": "#cbddf1", 
        "surface-container-highest": "#33353a", 
        "on-secondary-fixed-variant": "#8c1700", 
        "primary-container": "#44da4b", 
        "outline-variant": "#3d4a3a", 
        "surface-variant": "#33353a", 
        "inverse-on-surface": "#2e3035", 
        "surface-container": "#1e2024", 
        "secondary": "#ffb4a4", 
        "secondary-fixed": "#ffdad3", 
        "on-primary-fixed": "#002202", 
        "surface-bright": "#37393e", 
        "tertiary-fixed": "#d3e4f8", 
        "secondary-fixed-dim": "#ffb4a4", 
        "background": "#111318", 
        "surface-container-lowest": "#0c0e13", 
        "surface-container-low": "#191c20", 
        "on-tertiary-fixed": "#0b1d2b", 
        "on-background": "#e2e2e9"
      },
      borderRadius: {
        DEFAULT: "0.25rem", 
        lg: "0.5rem", 
        xl: "0.75rem", 
        full: "9999px"
      }, 
      spacing: {
        "space-md": "1rem", 
        "space-xs": "0.25rem", 
        "margin-desktop": "3rem", 
        "gutter": "1rem", 
        "margin": "1rem", 
        "space-xl": "2.5rem", 
        "space-lg": "1.5rem", 
        "margin-tablet": "2rem", 
        "gutter-desktop": "1.5rem", 
        "space-sm": "0.5rem"
      }, 
      fontFamily: {
        "headline-md": ["Syne", "sans-serif"], 
        "label-mono": ["JetBrains Mono", "monospace"], 
        "code-lg": ["JetBrains Mono", "monospace"], 
        "headline-lg-mobile": ["Syne", "sans-serif"], 
        "body-sm": ["Plus Jakarta Sans", "sans-serif"], 
        "body-md": ["Plus Jakarta Sans", "sans-serif"], 
        "display-xl": ["Syne", "sans-serif"], 
        "code-md": ["JetBrains Mono", "monospace"], 
        "body-lg": ["Plus Jakarta Sans", "sans-serif"], 
        "headline-sm": ["Syne", "sans-serif"], 
        "ticker-mono": ["JetBrains Mono", "monospace"], 
        "headline-lg": ["Syne", "sans-serif"], 
        "display-xl-mobile": ["Syne", "sans-serif"], 
        "headline": ["Syne", "sans-serif"], 
        "display": ["Syne", "sans-serif"], 
        "body": ["Plus Jakarta Sans", "sans-serif"], 
        "label": ["JetBrains Mono", "monospace"]
      }, 
      fontSize: {
        "headline-md": ["28px", {lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700"}], 
        "label-mono": ["11px", {lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600"}], 
        "code-lg": ["15px", {lineHeight: "24px", fontWeight: "500"}], 
        "headline-lg-mobile": ["28px", {lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700"}], 
        "body-sm": ["13px", {lineHeight: "20px", fontWeight: "400"}], 
        "body-md": ["15px", {lineHeight: "24px", fontWeight: "400"}], 
        "display-xl": ["64px", {lineHeight: "70px", letterSpacing: "-0.04em", fontWeight: "800"}], 
        "code-md": ["13px", {lineHeight: "20px", fontWeight: "400"}], 
        "body-lg": ["18px", {lineHeight: "28px", fontWeight: "400"}], 
        "headline-sm": ["20px", {lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600"}], 
        "ticker-mono": ["12px", {lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700"}], 
        "headline-lg": ["40px", {lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700"}], 
        "display-xl-mobile": ["38px", {lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "800"}]
      }
    }
  },
  plugins: [],
}
